### ISSUE TITLE
Have a preview in scene mode

### ISSUE THREAD

**Issue by KirbX** [SFraissTU/BA_PointCloud#16]
Hi! 
First of all, awesome project! It does works very well (for the things I tried actually!).
I only got one question, is it possible to have a preview in the scene mode (instead of only in game mode)? I would like to add some 3D objects to the scene, but since I can't see the pointcloud, I don't know where I should put my objects! 

Thanks a lot !
Best regards,

Raphaël

**Comment by SFraissTU** [comment]
Hi! No, unfortunately that's not possible yet.
Simon

**Comment by KirbX** [comment]
Hi! Thanks for your fast answer! No problems! Thanks!! :)

**Comment by SFraissTU** [comment]
Hey! Just want to let you know, that previewing is now possible! See the readme of this repo for more info!
Cheers!
