### ISSUE TITLE
temporarily hide the pointcloud

### ISSUE THREAD

**Issue by lfscetvr** [SFraissTU/BA_PointCloud#20]
for my vr-project i sometimes need temporarily switch off the pointcloud . if i disable the dynamic point cloud set script and re-enable the object later the pointcloud will not reload.
is is possible somehow to hide the pointcloud during runtime so that i can recall it later?

**Comment by SFraissTU** [comment]
Hi!
Yes, this is possible via code! To hide the point cloud you have to call:
`dynamicPointCloudSet.PointRenderer.Hide()`
and to display it again later, just call:
`dynamicPointCloudSet.PointRenderer.Display()`
I hope this helps.
Simon

**Comment by lfscetvr** [comment]
thank you very much, i will try this today
