### ISSUE TITLE
Port to PotreeConverter 2.0.2

### ISSUE THREAD

**Issue by siamonas** [SFraissTU/BA_PointCloud#27]
Hey there,

The recent [PotreeConverter](https://github.com/potree/PotreeConverter) release ([2.0.2](https://github.com/potree/PotreeConverter/releases/tag/2.0.2)) features a huge improvement performance-wise; it only creates 3 files now.

I think this is something that would boost the performance of the PointCloudRenderer as well. Are you currently considering adding support for PotreeConverter 2.0.2?

**Comment by SFraissTU** [comment]
Hi! While I currently don't plan on implementing the new format, GitHub user agressin has stated interest in implementing support for the new format. See discussion at pull request #29 .
So it might come eventually.
