### ISSUE TITLE
VR Stereo Rendering

### ISSUE THREAD

**Issue by EphTron** [SFraissTU/BA_PointCloud#41]
I ran into the problem of only seeing the point cloud on my left eye.

When using OpenXR or Oculus SDK make sure to set your Render Mode in the XR Project Settings from "Single Pass" to "Multi Pass".
Now it works like a charm!

I guess a short hint in the Getting Started or FAQ VR section might help some beginners.
Great plugin!

**Comment by SFraissTU** [comment]
Thanks! I added your suggestion to the readme!
