### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by pdavilaUM** [SFraissTU/BA_PointCloud#7]
Hi,
You did a fantastic job!!!

Models won't load in macOS without replacing the \ with /.  

For example:
//string dataRPath = node.MetaData.cloudPath + node.MetaData.octreeDir + "\\r\\";
string dataRPath = node.MetaData.cloudPath + node.MetaData.octreeDir + "/r/";

///if (!cloudPath.EndsWith("\\")) {

**Comment by SFraissTU** [comment]
Thanks a lot for the info. This will be fixed in my next update and is already fixed on my [current working branch](https://github.com/SFraissTU/BA_PointCloud/commit/aaf022dbb3657e4dfc8709e8786f566c8398d94d).
Simon
